backend:
  name: github
  repo: pkoenders/pixl
  use_graphql: true


media_folder: src/images
public_folder: /images 
logo_url: src/images/logo-pixl.inline.svg
display_url: https://pkoenders-pixl.netlify.app

publish_mode: editorial_workflow

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: settings
    label: Settings
    files:
      - name: projectsOrder
        label: Projects Order
        file: src/content/netlifycms/settings/projectsOrder.md
        fields:
          - label: Projects List
            name: projectsList
            widget: list
            fields: 
              - label: Projects Name 
                name: projectName 
                widget: relation
                collection: projects
                searchFields: [title]
                valueField: title

  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: projects
    label: Project
    folder: src/content/netlifycms/projects/
    media_folder: '{{repo}}/src/images'
    public_folder: '../../../../images'
    slug: '{{title}}'
    path: '{{slug}}/index'
    create: true
    fields:
      - label: 'Post Type' 
        name: 'posttype'
        widget: 'hidden'
        default: 'projectNetlifyCMS'

      - label: "Title" 
        name: "title"
        required: true

      - widget: string
        name: slug
        label: Slug (URL)
        required: true
        pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$','A slug can have no spaces or special characters']
        hint: >-
          The unique post URL (do not include folder or file extension)
    
      - label: "Date" 
        name: "date"
        widget: "datetime"

      - label: "Add to homepage"
        name: "addtohomepage"
        widget: "boolean"
        required: false

      - label: "Category"
        name: "categories"
        widget: "select"
        options: ["Website", "Print", "Branding"]
        default: ["Website"]

      - label: "Intro"
        name: "intro"
        required: false

      - label: "Cover Image"
        name: "coverimage"
        widget: "image"
        media_library:
          config:
          multiple: false
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown"